apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-app
  template:
    metadata:
      labels:
        app: websocket-app
    spec:
      containers:
      - name: websocket-app
        image: localhost:32000/chatty:0.0-202506161636
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-app-service
spec:
  selector:
    app: websocket-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30002
  type: NodePort